### ISSUE TITLE
When did you start doing Umbraco and why ?

### ISSUE THREAD

**Issue by dawoe** [mattbrailsford/ama#13]

**Comment by mattbrailsford** [comment]
It was back in 2010 whilst I was working at Amaze in Manchester. We were working with an in house CMS at the time and someone suggested I take a look at Umbraco. I did, and it changed everything :)

We didn't use it at work for a while, but I was so interested I started playing with it in my spare time and also started using it for my freelance work I was doing on the side. The more I used it the more I fell in love with it.

Fun fact, I did come across it earlier in my career when I was researching CMS's at a previous job, but I dismissed it because I didn't like the blue icons at the time :) (this was back in early v4 days).
