### ISSUE TITLE
Hobbies & stuff (kinda multi-part question - sorry!)

### ISSUE THREAD

**Issue by jamiepollock** [mattbrailsford/ama#2]
Hey Matt,
I know you're a big fan of hobbyist electronics. A few questions around this.

1. When did you first decide to get into this?
2. Do you have any advice of where to start?
3. Do you think having a hobby that revolves around problem solving helps with your day job of being a web/app developer?

Thanks,  
Jamie

**Comment by mattbrailsford** [comment]
Hey @jamiepollock 

1. I've always had an interest in electronics from an early age, I can always remember being inquisitive how things work and pretty much any toy I used to own got taken apart to see how it works (I wasn't so good at the putting back together part though). I'd also hack little projects together, such as creating my own bedroom burglar alarm by duck taping a cassette recorder to the back of the door, and breaking out the battery terminals to wires that would touch when the door opens playing a recording :) I didn't really get into it properly though until a few years ago when I became more aware of the Maker movement. I've been an avid hobbyist maker ever since.
2. I will warn you, hardware hacking can get pretty expensive buying all the kit, but you can get started with some pretty inexpensive gear. I'd say pick yourself up an [Arduino starter kit](https://shop.pimoroni.com/products/genuino-starter-kit) and a [project book](https://shop.pimoroni.com/products/make-basic-arduino-projects) and just start playing.
3. I personally use electronics as a break from my usual coding so it mainly helps me by giving me something else to think about for a while. That said, both are about problem solving so there is a lot of cross over and my coding experience definitely helped my cross over. Given the way the world is going though, there may be more crossover and influence as hardware becomes more integrated into our work and personal space.
