### ISSUE TITLE
What's Your Beard Regimen?

### ISSUE THREAD

**Issue by cssquirrel** [mattbrailsford/ama#3]
It's a pretty epic beard. Let's be honest.

So what's the secret? How do you care for it? Or is that it in its natural beauty?

**Comment by mattbrailsford** [comment]
Haha, I knew that one wouldn't take long :)

I did start out with all the oils and shampoos and stuff, but I'm actually pretty neglectful these days. I'll usually just wash it with hair shampoo whilst I'm showering and then give it a bit if a trim myself every few weeks (nobody else is allowed to touch it).

The only other thing I do though is to blow dry it every day (insert laughter here). I think that's probably the number one thing you can do though to keep it looking neat and well groomed as otherwise I just look like a hobo :)

**Comment by ismailmayat** [comment]
The world needs more beards @cssquirrel so get growing also it makes you a better developer fact!
