### ISSUE TITLE
What do you do to keep your mind, body and spirit in working order?

### ISSUE THREAD

**Issue by rbaty-barr** [mattbrailsford/ama#6]

**Comment by mattbrailsford** [comment]
I'm actually pretty bad at this and often end up swinging from extreme to extreme. 

Health wise, I've always struggled with my weight and at one point reached the 20st mark which I think was during my uni years which were actually pretty hard for me as I was up to my eyeballs in student debt and couldn't afford to do anything so turned to food for comfort. I managed to get myself down to 15st at one point, but I still struggle with food and have since risen to my current weight of 17st which I'm not happy about.

Unfortunately exercise to me is just torture. I really don't get people who enjoy it :) Because of this, again, I tend to swing from over doing it to not doing it at all. In the past I've done Capoeira and got quite good at running, but after knackering my knee ended up giving them up and wasting away again. I'm currently trying to get back into things and am hitting the gym every other morning just doing 30 minute workouts as something is better than nothing right?

Mind wise, I really don't look after it like I should which is stupid since it's my primary tool. I have my hobbies which help distract me, but my natural swing mentality often means I over do these as well causing me extra stress. I really should do more to look after my mind though. Once of my best experiences was actually when I went to Angular Connect where they had a quiet room and had a Mindfulness guy there teaching meditation. It was the best half hour I'd had in a long time, but me being me, I haven't done it since :(
