### ISSUE TITLE
How can we (as devs, agencies, community & HQ) improve and grow the Umbraco package ecosystem?

### ISSUE THREAD

**Issue by barryokane** [mattbrailsford/ama#7]

**Comment by mattbrailsford** [comment]
Very interesting question, and one I ponder myself being an active package dev for such a long time.

I think package dev is starting to get a lot more polished, where the old ethos was to just package up what you've made and let other people use it, now people are thinking a lot more beyond their own needs and creating really useful, robust and professional packages.

I think the biggest thing that can help package dev move forwards is to stop thinking that everything needs to be free (or that beer is an acceptable payment method). Free was fine when it was just throwing what you've built together and sharing with people "as is", but the amount of work people are putting into packages these days, and the ongoing demand they have to deal with in support, should not be taken lightly and I think these people should be rewarded appropriately for their efforts, especially at the agency level where these tools are saving agencies loads of money on in-house dev hours. 

If we can get past everyone thinking things should be free, then package devs can start to feel like the effort they put in is worth it and they can spend more time doing what they love, rather than having to do a full time job as well to be able to support themselves. 

@LeeKelleher and I are attempting an interesting take on this by starting a [patreon page](https://www.patreon.com/umco) where we urge developers and agencies to consider funding on an on-going basis to help keep development going. By doing it this way, we don't charge for any particular package, keeping these free, but we still manage to have a reasonable income to help support the various projects. This is still early days for us though and we haven't managed to push it as much as we would like yet, but we will be doing more in the future so we'll see how it goes.

From a HQ perspective, I think it would be nice to see more engagement with package devs, maybe through a "package devs" support network, where people who take package dev seriously could get advice on best ways to integrate with Umbraco. At then end of the day, quality packages will benefit everyone so it only makes sense to nurture it.

**Comment by JeffreyPerplex** [comment]
Hi Matt,

thanks for raising this topic and I gave the topic a lot of thought over the past couple of months. We've developed and released three packages of the last couple of years which got several downloads (1,500 each) but the more downloads, the more questions you get. 

The thought behind releasing these packages is to contribute to the community and I still think that was the best thing todo. We had the code already somehow ready when we we're starting the package, but it takes a lot of time making the package really 'package-ready', including testing, documenting and after release bugfixing some edge-cases, maintaining it, and make it compatible with every new Umbraco-version. I really underestimated the time this takes sometimes (and I don't have a package with that much downloads as you guys probably having).

I wrote a blog two years ago on usermanagement (http://skrift.io/articles/archive/i-have-a-dream-about-user-management-in-umbraco/), and have been developing some parts of it in the last couple of months, but as stated in the comments by Niels it will probably take 1000+ hours to fully develop it, and maybe 250+ hours to develop a proper first version of the package. I have been thinking about how I could justify this effort to my company and that it's worth investing and then releasing it and that's almost undoable. Some thoughts that go around in my head is releasing it as a paid package (€ 129 one time fee, the same as Umbraco asks for their packages) but every developer that's contributing to Umbraco in one way or another (writing a blog post, developed a package, organized a conference or meet-up, asking or answering questions on Our, etc.) could apply for a free license that is almost granted for sure. No matter how big or small your contribution is, if you think it's worth a free license; be my guest. And if you're contributing a lot, you can have more licenses for free. And for all those companies that are just using Umbraco, what is perfect of course, would have to pay a small licensing fee to gain a lot of functionality. 

I like your idea of the patreon page, but would love to see it in a broader perspective for all package devs to benefit from. But that raises questions about how to split the funding afterwards. And just to make sure; it's not about the money per se, and I don't think anybody will ever get rich of this, but it's just some compensation for all the work that some people invest in make really good packages.

Love to continue the discussion, and give it some serious discussion during CodeGarden. Hope to see you there,

Jeffrey
