### ISSUE TITLE
Cheif Umbraco Unicorn for one week

### ISSUE THREAD

**Issue by drpeck** [mattbrailsford/ama#8]
This is fun! I like this project.

If you were made Chief Umbraco Unicorn for just one week, what would you change?

**Comment by mattbrailsford** [comment]
Wow, this is a really hard question, especially for a package dev as usually if I'm not happy with something in Umbraco, I just develop a package to change it :)

The only thing I can think of is to move CodeGarden back to central CPH, but that's just because I'm currently planning my CG trip and being far from the airport stresses me out when I'm in other countries :)
